### ISSUE TITLE
[BUG] AAS Web UI does not display any information when certain threshold (400k) of AAS/SM is reached on the environment

### ISSUE THREAD

**Issue by JBlezi** [eclipse-basyx/basyx-aas-web-ui#295]
**Describe the bug**
The AAS Web UI does not function properly when there are many AAS (more than 400000) present on the environment. Nothing is being displayed, instead, the loading wheel just spins forever.

**To Reproduce**
1. Start Basyx Docker setup (2.0.0-SNAPSHOT) including AAS Environment, AAS Registry, SM Registry, AAS Discovery & AAS Web UI (v2-241114)
2. Upload at least 400000 AASX files with at least 1 SM each using the /upload endpoint
3. Try to access the AAS Web UI

**Expected behavior**
AAS Web UI does not show any of the uploaded shells, instead the loading wheel spins forever. 

**BaSyx (please complete the following information):**
- BaSyx Version 2.0.0-SNAPSHOT
- BaSyx Docker
- AAS Version 

DotAAS V3

**Screenshots**
<img width="865" alt="Image" src="https://github.com/user-attachments/assets/701716c1-d07e-49aa-9c78-0e3d1c52ed4a" />

**Used Asset Administration files (.aasx/.json/.xml)**
Not possible to upload AASX files here.

**BaSyx configuration**
```
version: "3.7"

services:
  mongodb:
    image: mongo:5.0.10
    volumes:
      - mongodb-data-version-5.0.10:/data/db
    container_name: mongodb-aasreg-smreg-v3
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_EXTRA_FLAGS: --wiredTigerCacheSizeGB=4
    deploy:
      resources:
            limits:
              memory: 8G
              cpus: '4'
            reservations:
              memory: 4G
              cpus: '2'
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "3"

  aas-registry-service:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name:  aas-registry-v3
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - 8050:8080
    depends_on:
      - mongodb
    restart: always

  submodel-registry-service:
    image: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name:  submodel-registry-v3
    # pull_policy: never
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - 8051:8080
    depends_on:
      - mongodb
    restart: always

  aas-environment-service:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    volumes:
    - ./application.properties:/application/application.properties
    container_name:  aas-environment-v3
    # pull_policy: never
    ports:
      - 8082:8081
    environment:
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://aas-registry-service:8080 # <--- to register the AAS in the AAS registry
      BASYX_EXTERNALURL: http://localhost:8082 # <--- to create the connection from the registry to the environment
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://submodel-registry-service:8080 # <--- to register the submodels in the submodel registry
    depends_on:
      - mongodb
    restart: always

  aas-web-ui:
      image: eclipsebasyx/aas-gui:v2-241114
      container_name: aas-web-ui
      ports:
          - "3000:3000"
      environment:
          AAS_REGISTRY_PATH: "http://localhost:8050"
          SUBMODEL_REGISTRY_PATH: "http://localhost:8051"
          AAS_DISCOVERY_PATH: "http://localhost:8083"
          AAS_REPO_PATH: "http://localhost:8082/shells"
          SUBMODEL_REPO_PATH: "http://localhost:8082/submodels"
          CD_REPO_PATH: "http://localhost:8082/concept-descriptions"
          # DASHBOARD_SERVICE_PATH: "<dashboard_service_path>" (optional; Time Series Data)
          PRIMARY_COLOR: "#3DB60F"
          LOGO_PATH: "Logo/murrelektronik_logo-green.svg"    # BASE_PATH: "<base_path>" (optional)
          # INFLUXDB_TOKEN: "<influxdb_token>" (optional; Time Series Data)
          # KEYCLOAK_URL: "<keycloak_url>" (optional; RBAC feature)
          # KEYCLOAK_REALM: "<keycloak_realm>" (optional; RBAC feature)
          # KEYCLOAK_CLIENT_ID: "<keycloak_client_id>" (optional; RBAC feature)
      volumes:
       - /Users/juliusblezinger/Documents/Logo:/usr/src/app/dist/Logo
      depends_on:
        - aas-environment-service


  aas-discovery-service:
    image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
    container_name: aas-discovery-service
    volumes:
      - ./application.properties:/application/application.properties
    ports:
      - 8083:8081
    environment:
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      - mongodb
      - aas-environment-service
      - aas-registry-service
      - submodel-registry-service
    restart: always

volumes:
   mongodb-data-version-5.0.10:
      driver: local
```

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.3
 - Browser: chrome

**Additional context**
