### ISSUE TITLE
AASX Download doesn't work

### ISSUE THREAD

**Issue by HansG89** [eclipse-basyx/basyx-aas-web-ui#371]
Hello,

I'm running the BaSyx Environment repository and the BaSyx UI in Docker Compose.

This is a simplified configuration:

```yaml
services:
  repository:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    ports:
      - 8081:8081
    volumes:
       - ./application.properties:/application/application.properties
  ui:
    image: eclipsebasyx/aas-gui:SNAPSHOT
    ports:
      - 3000:3000
    environment:
      AAS_REPO_PATH: http://localhost:8081
      SUBMODEL_REPO_PATH: http://localhost:8081
      CD_REPO_PATH: http://localhost:8081
```

As you can see I provided `AAS_REPO_PATH`, `SUBMODEL_REPO_PATH` and `CD_REPO_PATH` and they are also showing up in the configuration menu of the UI.

![Image](https://github.com/user-attachments/assets/aa9b6538-6d9a-4a0e-b5ab-c440cdc79c55)

When I'm trying to download one of my shells, the Download URL get's incorrectly constructed. The `AAS_REPO_PATH` is not taken into account. 

This is how the invoked request looks like:

```bash
http://serialization/?aasIds=SOME_AAS_ID&submodelIds=SOME_SUBMODEL_ID&includeConceptDescriptions=true
```

What am I missing?
